# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8974be66a1830f419f839c849ddc6839b4ed0780502d8c17f35b215af08e6a8289ce7c2f964e1ee6e15bb8f5b334925c1616170de04c81c491f20fabfc8efb1

test:
  secret_key_base: b43b7a1221decddb34d97bac25b117d8aed5dbf0758d5c1e5fadba4f11eec55d01503094546035c679308ba3de9a3a87cdcaaed88f4fc7a683ab88a9bb419d13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
